apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-destined-dog
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "781790230841"
    project: brifer-terraform-admin
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: briferz-x
    repository: jx3-gke-vault
  - key: staging
  - key: production
  ingress:
    domain: 35.239.51.71.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: briferzx
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: gs://logs-tf-jx-destined-dog-3b3fbaa36800
  - name: reports
    url: gs://reports-tf-jx-destined-dog-3b3fbaa36800
  - name: repository
    url: gs://repository-tf-jx-destined-dog-3b3fbaa36800
  terraformVault: true
  vault:
    bucket: vault-tf-jx-destined-dog-3b3fbaa36800
    key: crypto-key-tf-jx-destined-dog-3b3fbaa36800
    keyring: keyring-tf-jx-destined-dog-3b3fbaa36800
    name: tf-jx-destined-dog
    serviceAccount: tf-jx-destined-dog-vt
  webhook: lighthouse
