filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: dev
  url: http://chartmuseum-jx.35.239.51.71.nip.io
releases:
- chart: jxgh/jx-verify
  name: jx-verify
  namespace: jx-staging
  values:
  - jx-values.yaml
- chart: dev/python-http
  version: 0.0.1
  name: python-http
  namespace: jx-staging
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
