filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: dev
  url: http://chartmuseum-jx.35.239.51.71.nip.io
releases:
- chart: jxgh/jx-verify
  name: jx-verify
  namespace: jx-production
  values:
  - jx-values.yaml
- chart: dev/jx-payments-manning
  version: 0.0.3
  name: jx-payments-manning
  namespace: jx-production
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
